name: photoz
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - astropy
  - hyperas
  - joblib
  - jupyter
  - matplotlib
  - numpy
  - pip
  - scipy
  - setuptools
  - tensorflow
  - pip:
    - hyperopt
    - lightgbm
    - pandas
    - scikit-learn
    - seaborn
    - sklearn
    - tqdm
    - vos
    - xgboost
